### ISSUE TITLE
Unable to select terms and conditions checkbox upon reading through and scrolling all the way down

### ISSUE THREAD

**Issue by 4the1appsllc** [Microsoft/clarity-js#115]

**Comment by ssivov** [comment]
Can you please say which browser you were using?

**Comment by ssivov** [comment]
Closing, since this is not related to the clarity-js telemetry library. For questions and comments about www.clarity.ms please contact us at clarityms@microsoft.com.

**Comment by ssivov** [comment]
Potential cause discovered:
Scroll offset calculation is flaky when browser window is zoomed

**Comment by ssivov** [comment]
@4the1appsllc , the problem has now been fixed, please try creating your project again.
